import figlet from 'figlet'
import { writeFileSync } from 'node:fs'

const FONT = 'ANSI Shadow'

// Render letters one at a time with exactly one blank column after each; the default layout smushes NITH together.
const art = (text) => {
  const glyphs = [...text].map((ch) => {
    const rows = figlet.textSync(ch, { font: FONT }).split('\n')
    const width = ch === ' ' ? 3 : Math.max(...rows.map((r) => r.trimEnd().length)) + 1
    return rows.map((r) => r.trimEnd().padEnd(width))
  })
  const height = Math.max(...glyphs.map((g) => g.length))
  return Array.from({ length: height }, (_, i) => glyphs.map((g) => g[i] ?? ' '.repeat(g[0].length)).join(''))
    .map((l) => l.trimEnd())
    .filter((l) => l.trim())
    .join('\n')
}

const one = art('JASON SONITH')
const stacked = `${art('JASON')}\n\n${art('SONITH')}`

writeFileSync(
  'src/data/ascii-name.ts',
  `// Generated by scripts/ascii-name.mjs (figlet "${FONT}"). Do not edit.\nexport const ASCII_NAME = ${JSON.stringify(one)}\nexport const ASCII_NAME_STACKED = ${JSON.stringify(stacked)}\n`,
)
console.log(one)
