import figlet from 'figlet'
import { writeFileSync } from 'node:fs'

const art = (text) =>
  figlet
    .textSync(text, { font: 'ANSI Shadow' })
    .split('\n')
    .map((l) => l.trimEnd())
    .filter((l) => l.trim())
    .join('\n')

const one = art('JASON SONITH')
const stacked = `${art('JASON')}\n\n${art('SONITH')}`

writeFileSync(
  'src/data/ascii-name.ts',
  `// Generated by scripts/ascii-name.mjs (figlet "ANSI Shadow"). Do not edit.\nexport const ASCII_NAME = ${JSON.stringify(one)}\nexport const ASCII_NAME_STACKED = ${JSON.stringify(stacked)}\n`,
)
console.log(one)
